// <auto-generated />
using System;
using Craftsmanship.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Craftsmanship.Infrastructure.Migrations
{
    [DbContext(typeof(CraftsmanshipDbContext))]
    [Migration("20260201060551_AddScanTeamForeignKey")]
    partial class AddScanTeamForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Craftsmanship.Infrastructure.Persistence.Entities.ScanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Aspect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodebasePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamKey");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("Craftsmanship.Infrastructure.Persistence.Entities.ScoreSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Aspect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubScores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScoreSnapshots");
                });

            modelBuilder.Entity("Craftsmanship.Infrastructure.Persistence.Entities.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamKey")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Craftsmanship.Infrastructure.Persistence.Entities.ScanEntity", b =>
                {
                    b.HasOne("Craftsmanship.Infrastructure.Persistence.Entities.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamKey")
                        .HasPrincipalKey("TeamKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
