// <auto-generated />
using Craftsmanship.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Craftsmanship.Infrastructure.Migrations
{
    [DbContext(typeof(CraftsmanshipDbContext))]
    partial class CraftsmanshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");
#pragma warning restore 612, 618
        }
    }
}
